# Generated by Django 3.1.2 on 2021-12-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210409_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='userid',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='books',
            name='id',
        ),
        migrations.RemoveField(
            model_name='books',
            name='username',
        ),
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
